{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "gpuType": "T4"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    },
    "accelerator": "GPU"
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 4,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Q_GG-CUczvrS",
        "outputId": "a1cd08b1-6e7b-47d8-f7d0-985456dcba1a"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Overwriting sample.json\n"
          ]
        }
      ],
      "source": [
        "%%writefile sample.json\n",
        "[\n",
        "    {\n",
        "        \"title\": \"Issue with Time Configuration in xlreporter\",\n",
        "        \"body\": \"\\n                \\nI'm experiencing issues with xlreporter when graphing data from an SQL query. In my SQL query, I select and filter data using the following query:\\nSELECT PT102_PV, t_stamp FROM group_table WHERE t_stamp BETWEEN '2024-07-30 00:00' AND '2024-07-31 00:00' AND PT102_PV IS NOT NULL ORDER BY t_stamp DESC;\\nIn the SQL query, the date and time are displayed correctly. However, when I configure xlreporter to plot PT102_PV based on the date and time from t_stamp, the time is not being interpreted correctly. The date is correct, but the time appears to be incorrect or misinterpreted. I have checked that xlreporter is set to use the date and time from t_stamp, but the issue persists.\\nHas anyone experienced a similar issue or have suggestions on how to resolve this?\\nI reviewed the configuration in xlreporter and ensured that the date and time format matches that of my SQL query. I also tried different settings in xlreport to adjust the format of the graph axes and make sure the time is interpreted correctly. However, the time still appears incorrectly on the graphs, while the date is displayed correctly.\\nI expected xlreporter to correctly interpret both the date and time from t_stamp and for the graph to accurately reflect these data, showing the correct time for each PT102_PV value.\\ncomparative image SQL query and XLreporter query (SQL Correct)\\nXLReport Configuration\\n    \",\n",
        "        \"tags\": [\n",
        "            \"datetime\",\n",
        "            \"reporting-services\",\n",
        "            \"visualization\",\n",
        "            \"reporting\",\n",
        "            \"error-reporting\",\n",
        "            \"datetime\",\n",
        "            \"reporting-services\",\n",
        "            \"visualization\",\n",
        "            \"reporting\",\n",
        "            \"error-reporting\"\n",
        "        ],\n",
        "        \"link\": \"https://stackoverflow.com/questions/78836459/issue-with-time-configuration-in-xlreporter\",\n",
        "        \"score\": \"\\n0        \",\n",
        "        \"creation_date\": \"2024-08-05T21:10:11\",\n",
        "        \"answer_count\": \"0\",\n",
        "        \"comments\": [\n",
        "            \"I assume the time zone on your sql server, SSRS server, and client aren't 4 hours apart.\",\n",
        "            \"yes, the configuration of sql server, the ssrs server and the client are set to the same time zone.  now, I'm not using ssrs since for reporting because I'm using xlreporter. thanks for your response\"\n",
        "        ],\n",
        "        \"answers\": [],\n",
        "        \"selected_answer\": null,\n",
        "        \"images\": []\n",
        "    },\n",
        "    {\n",
        "        \"title\": \"How to display an image(as error) instead of error message\",\n",
        "        \"body\": \"\\n                \\nconst FALLBACK_IMAGE = \\\"https://devprojectupload.s3.ap-south-1.amazonaws.com/32490.png\\\";\\n\\n\\nconst ModelComponent = (props) => {\\n\\n  const [height, setHeight] = useState(window.innerHeight);\\n  const [width, setWidth] = useState(window.innerWidth);\\n  \\n  //API data \\n  const [modelData, setModelData] = useState([]);\\n  \\n  //Error\\n  const [isError, setIsError] = useState(\\\"\\\");\\n\\n\\nuseEffect(() => {\\naxios.\\nget(\\\"https://51fgc922b7.execute-api.ap-south-1.amazonaws.com/dev/productpreview\\\")\\n.then((res) => {\\nconsole.log(res.data.data)\\nsetModelData(res.data.data[0])\\n})\\n.catch((error)=>\\nsetIsError(()=>{\\n, error\\n})\\n)\\n}, []);\\n\\n    \",\n",
        "        \"tags\": [\n",
        "            \"reactjs\",\n",
        "            \"onerror\",\n",
        "            \"reactjs\",\n",
        "            \"onerror\"\n",
        "        ],\n",
        "        \"link\": \"https://stackoverflow.com/questions/74327725/how-to-display-an-imageas-error-instead-of-error-message\",\n",
        "        \"score\": \"\\n-1        \",\n",
        "        \"creation_date\": \"2022-11-05T12:34:34\",\n",
        "        \"answer_count\": \"1\",\n",
        "        \"comments\": [\n",
        "            \"What about creating new Error Component and redirect error to that component routes,Have you tried this\",\n",
        "            \"Format your code correctly, please\",\n",
        "            \"Thank you for your response. It helped me to resolve the issue.\"\n",
        "        ],\n",
        "        \"answers\": [\n",
        "            {\n",
        "                \"body\": \"\\nCurrently you're not returning anything in your setIsError function. You can return the error you receive from the catch or just set it to true\\nsetIsError(()=>{\\n  return error;\\n  // return true;\\n})\\n\\nIn the return of your component you could do something like this, where you check if there is an error and if there is you display your img\\nreturn (\\n  ...\\n  {isError && <img src={FALLBACK_IMAGE} alt=\\\"error\\\"/>}\\n  ...\\n);\\n\\n    \",\n",
        "                \"score\": null\n",
        "            }\n",
        "        ],\n",
        "        \"selected_answer\": null,\n",
        "        \"images\": []\n",
        "    },\n",
        "    {\n",
        "        \"title\": \"nuxtjs vuejs @error is not firing in a component when trying to load a fallback image\",\n",
        "        \"body\": \"\\n                \\nI have a component that I feed with props.\\nWhen an image throws a 404 I want to load a fallback image. So far so good.\\nHowever the @error function never fires when an image is broken and I can't figure out why! I never get 'hello event' in the console.\\nThe component is on the first level of a nuxt page, my setup is a static SPA.\\nI tried to implement it as mentioned at the end of this github issue: https://github.com/vuejs/vue/issues/5404\\n<template>\\n  <div class=\\\"channel\\\">\\n     <div class=\\\"img\\\">\\n       <img :src=\\\"imgUrl\\\" :alt=\\\"name\\\" :title=\\\"name\\\" @error=\\\"getFallBackImage\\\" />\\n     </div>\\n  </div>\\n</template>\\n\\n<script>\\n  export default {\\n    data: function() {\\n      return {\\n        chanCover: this.cover\\n      }\\n    },\\n    props: {\\n      name: {\\n        type: String,\\n        required: true\\n      },\\n      cover: {\\n        type: String,\\n        required: true\\n      }\\n    },\\n    computed: {\\n      imgUrl() {\\n        console.log(this.chanCover)\\n        return \\\"channels/\\\"+this.chanCover+\\\".jpg\\\"\\n      },\\n    },\\n    methods: {\\n      getFallBackImage(event) {\\n        console.log(\\\"hello event\\\")\\n        this.chanCover = \\\"default\\\"\\n      }\\n    }\\n  }\\n</script>\\n\\n\\n    \",\n",
        "        \"tags\": [\n",
        "            \"javascript\",\n",
        "            \"vue.js\",\n",
        "            \"nuxt.js\",\n",
        "            \"onerror\",\n",
        "            \"javascript\",\n",
        "            \"vue.js\",\n",
        "            \"nuxt.js\",\n",
        "            \"onerror\"\n",
        "        ],\n",
        "        \"link\": \"https://stackoverflow.com/questions/71610447/nuxtjs-vuejs-error-is-not-firing-in-a-component-when-trying-to-load-a-fallback\",\n",
        "        \"score\": \"\\n0        \",\n",
        "        \"creation_date\": \"2022-03-24T23:10:39\",\n",
        "        \"answer_count\": \"0\",\n",
        "        \"comments\": [\n",
        "            \"Not sure about the github issue but I've seen \",\n",
        "            \", hope it may help. PS: mentioning me like that in the comments doesn't me any kind of notification. \",\n",
        "            \" if you want me to be 100% sure of seeing your question.\",\n",
        "            \"Thanks for the pointer @kissu that might actually work!\",\n",
        "            \"Keep us updated.\",\n",
        "            \"I am still curious why error is not working here, but I switched everything towards webpack so the proposed solution did work! Thanks a bunch.\",\n",
        "            \"What were you using before?\"\n",
        "        ],\n",
        "        \"answers\": [],\n",
        "        \"selected_answer\": null,\n",
        "        \"images\": []\n",
        "    },\n",
        "    {\n",
        "        \"title\": \"onerror javascript loads just once?\",\n",
        "        \"body\": \"\\n                \\nI've been trying to figure out the way for loading screen on/off as I choose (not by automatical event).\\nso I came up with this solution:\\ncss:\\n#loading {\\n    display: block;\\n    position: absolute;\\n    top: 0;\\n    left: 0;\\n    z-index: 100;\\n    width: 100vw;\\n    height: 100vh;\\n    background-color: rgba(192, 192, 192, 0.5);\\n    background-image: url(\\\"https://i.sstatic.net/MnyxU.gif\\\");\\n    background-repeat: no-repeat;\\n    background-position: center;\\n}\\n\\njavascript:\\nfunction loading(action) {\\n    console.log(action);\\n    document.getElementById('loading').style.display = action ? 'block' : 'none';\\n}\\n\\nhtml:\\n<div id=loading></div>\\n<img onerror=\\\"loading(true)\\\">\\n// do whatever i need, which takes several seconds to load\\n<img onerror=\\\"loading(false)\\\">\\n\\nthe loading screen comes on as suppose to, with no problem whatsoever, however there are two things which are not clear to me...\\n\\nthe console.log(action) does not work... it just won't print anything to console whatsoever\\nsecond image won't turn off the loading screen... it just stays on all the time\\n\\nwhat do I do wrong here?\\n    \",\n",
        "        \"tags\": [\n",
        "            \"javascript\",\n",
        "            \"html\",\n",
        "            \"onerror\",\n",
        "            \"javascript\",\n",
        "            \"html\",\n",
        "            \"onerror\"\n",
        "        ],\n",
        "        \"link\": \"https://stackoverflow.com/questions/64268489/onerror-javascript-loads-just-once\",\n",
        "        \"score\": \"\\n1        \",\n",
        "        \"creation_date\": \"2020-10-08T18:19:56\",\n",
        "        \"answer_count\": \"1\",\n",
        "        \"comments\": [\n",
        "            \"I'm not sure what you expect to happen, but the \",\n",
        "            \" handler only gets called by an \",\n",
        "            \" element when there is an error loading the image.\",\n",
        "            \"exactly, this is an old trick how to trigger any javascipt call :) so there is no src in that img as you can see, because of that i can trigger onerror event which will call my javascript function to shot/hide loading screen... showing works fines, hiding not so much :(\",\n",
        "            \"I don't think it does. Your \",\n",
        "            \" div is already visible at the start (\",\n",
        "            \"), \",\n",
        "            \" is just not called at all. It would be called if you had a fake \",\n",
        "            \" attribute on it.\"\n",
        "        ],\n",
        "        \"answers\": [\n",
        "            {\n",
        "                \"body\": \"\\nAccording to @Aioros answer, it was partialy correct...\\nafter adding src to both  tags, then it tries to trigger the javascript function, however i was gettig error: loading is not a function which makes no sence to me.\\nso i have replaced:\\n<img src=blabla onerror=\\\"loading(true/false)\\\">\\n\\nwith:\\n<script>loading(true/false)</script>\\n\\nand it works just fine now...\\n    \",\n",
        "                \"score\": null\n",
        "            }\n",
        "        ],\n",
        "        \"selected_answer\": \"\\nAccording to @Aioros answer, it was partialy correct...\\nafter adding src to both  tags, then it tries to trigger the javascript function, however i was gettig error: loading is not a function which makes no sence to me.\\nso i have replaced:\\n<img src=blabla onerror=\\\"loading(true/false)\\\">\\n\\nwith:\\n<script>loading(true/false)</script>\\n\\nand it works just fine now...\\n    \",\n",
        "        \"images\": []\n",
        "    },\n",
        "    {\n",
        "        \"title\": \"Is there anyway to catch sandbox Uncaught/Unsafe error messages from cross-origin scripts\",\n",
        "        \"body\": \"\\n                \\nWhen adding an on error event listener, typically you will receive an ErrorEvent object full of details (message, line, column, etc) about the error message; however, when an error is thrown from a cross origin script, all you get is the \\\"Script error.\\\" message. From my understanding, this is done for security reasons.\\n\\nI am running into some problems because of this restriction. I have am running cross-origin scripts (not my scripts, they could come from anywhere, I don't control them, total randomness here) within an IFrame element where I have added an on error event listener and the \\\"sandbox\\\" attribute.\\n\\nMy goal was to report and sandbox violations that happened to the top level page. So for example, if the sandbox doesn't allow pop-ups. Within the console window an error message is displayed that says something like \\\"Pops are not allowed in a sandboxed environment\\\". The onerror picks up on the error, but when you inspect the message, it always says \\\"Script error\\\".\\n\\nIs there a different way for me to catch these uncaught/unsafe error messages?\\n\\nMy goal is to parse out the messages to see which sandbox violations are being thrown for logging. This method will not work, because any uncaught error message within the IFrame will get translated to the same message, which could lead to false positives. For example, someone does throw new Error('test') and now there is no way for me to tell if it was a sandbox error or a script error.\\n    \",\n",
        "        \"tags\": [\n",
        "            \"javascript\",\n",
        "            \"sandbox\",\n",
        "            \"onerror\",\n",
        "            \"javascript\",\n",
        "            \"sandbox\",\n",
        "            \"onerror\"\n",
        "        ],\n",
        "        \"link\": \"https://stackoverflow.com/questions/55793495/is-there-anyway-to-catch-sandbox-uncaught-unsafe-error-messages-from-cross-origi\",\n",
        "        \"score\": \"\\n2        \",\n",
        "        \"creation_date\": \"2019-04-22T11:15:34\",\n",
        "        \"answer_count\": \"1\",\n",
        "        \"comments\": [],\n",
        "        \"answers\": [\n",
        "            {\n",
        "                \"body\": \"\\nIf the Javascript error message is \\\"Script error.\\\", there is no way to extract the actual error message via Javascript. While the user can examine their browser console to see the error details, the cross-origin error details will not be exposed to your Javascript in any way, for security reasons.\\n\\nTo mitigate this, if at all possible, suggest that users use libraries from sites which do not have CORS restrictions. A site that hosts a library needs to have both\\n\\naccess-control-allow-origin: *\\naccess-control-expose-headers: *\\n\\n\\nin order to catch errors thrown in scripts hosted by that site. For example:\\n\\n<script src=\\\"https://cdn.jsdelivr.net/npm/[email\\u00a0protected]/babel.min.js\\\"></script>\\n\\n\\nBecause jsdelivr has both of those headers, errors thrown will be viewable. (Forgive the stack snippet hacks, but it demonstrates the issue:)\\n\\n\\r\\n\\r\\n-->\\r\\n</style>\\r\\n<script src=\\\"https://cdn.jsdelivr.net/npm/[email\\u00a0protected]/babel.min.js\\\"></script>\\r\\n</script>\\r\\n</head>\\r\\n<body>\\r\\n<script src=\\\"/scripts/snippet-javascript-console.min.js?v=1\\\"></script>\\r\\n<script type=\\\"text/babel\\\">Invalid syntax\\r\\n</style>\\r\\n<!--\\r\\n\\r\\n\\r\\n\\n\\nIf the library comes from a site without both of those headers, the error will be opaque. For example, this snippet is identical to the above, except that the link is to a site without access-control-expose-headers: *:\\n\\n\\r\\n\\r\\n-->\\r\\n</style>\\r\\n<script src=\\\"https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.10.3/babel.min.js\\\"></script>\\r\\n</script>\\r\\n</head>\\r\\n<body>\\r\\n<script src=\\\"/scripts/snippet-javascript-console.min.js?v=1\\\"></script>\\r\\n<script type=\\\"text/babel\\\">Invalid syntax\\r\\n</style>\\r\\n<!--\\r\\n\\r\\n\\r\\n\\n\\nIf you have no control at all over which library links the users use, there's nothing you can do to get access to the opaque errors, unless you can get them to install a custom browser extension (which has escalated privileges), or something like that.\\n    \",\n",
        "                \"score\": null\n",
        "            }\n",
        "        ],\n",
        "        \"selected_answer\": \"\\nIf the Javascript error message is \\\"Script error.\\\", there is no way to extract the actual error message via Javascript. While the user can examine their browser console to see the error details, the cross-origin error details will not be exposed to your Javascript in any way, for security reasons.\\n\\nTo mitigate this, if at all possible, suggest that users use libraries from sites which do not have CORS restrictions. A site that hosts a library needs to have both\\n\\naccess-control-allow-origin: *\\naccess-control-expose-headers: *\\n\\n\\nin order to catch errors thrown in scripts hosted by that site. For example:\\n\\n<script src=\\\"https://cdn.jsdelivr.net/npm/[email\\u00a0protected]/babel.min.js\\\"></script>\\n\\n\\nBecause jsdelivr has both of those headers, errors thrown will be viewable. (Forgive the stack snippet hacks, but it demonstrates the issue:)\\n\\n\\r\\n\\r\\n-->\\r\\n</style>\\r\\n<script src=\\\"https://cdn.jsdelivr.net/npm/[email\\u00a0protected]/babel.min.js\\\"></script>\\r\\n</script>\\r\\n</head>\\r\\n<body>\\r\\n<script src=\\\"/scripts/snippet-javascript-console.min.js?v=1\\\"></script>\\r\\n<script type=\\\"text/babel\\\">Invalid syntax\\r\\n</style>\\r\\n<!--\\r\\n\\r\\n\\r\\n\\n\\nIf the library comes from a site without both of those headers, the error will be opaque. For example, this snippet is identical to the above, except that the link is to a site without access-control-expose-headers: *:\\n\\n\\r\\n\\r\\n-->\\r\\n</style>\\r\\n<script src=\\\"https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.10.3/babel.min.js\\\"></script>\\r\\n</script>\\r\\n</head>\\r\\n<body>\\r\\n<script src=\\\"/scripts/snippet-javascript-console.min.js?v=1\\\"></script>\\r\\n<script type=\\\"text/babel\\\">Invalid syntax\\r\\n</style>\\r\\n<!--\\r\\n\\r\\n\\r\\n\\n\\nIf you have no control at all over which library links the users use, there's nothing you can do to get access to the opaque errors, unless you can get them to install a custom browser extension (which has escalated privileges), or something like that.\\n    \",\n",
        "        \"images\": []\n",
        "    },\n",
        "    {\n",
        "        \"title\": \"Image onError Handling in React\",\n",
        "        \"body\": \"\\n                \\nI am trying to grab the maxresdefault of multiple YouTube thumbnails. Some YouTube videos simply don't have a high res thumbnail photo so I want to catch that with an onError prop on an img element. For some reason my function is not triggering when I get the 404 img error. Any ideas? Thanks in advance.\\n\\nclass FeaturedVideo extends Component<Props> {\\n  addDefaultSrc = (e) => {\\n    e.target.src = this.props.background.replace(\\\"maxresdefault\\\", \\\"hqdefault\\\")\\n  }\\n\\n  renderVideo = (props) => (\\n    <div\\n      style={{\\n        width: \\\"100%\\\",\\n        height: \\\"100%\\\",\\n        backgroundSize: \\\"contain\\\",\\n      }}\\n      className=\\\"featured-community-video\\\"\\n    >\\n      <img onError={this.addDefaultSrc} src={props.background} alt=\\\"\\\" />\\n      <div className=\\\"featured-community-video-title\\\">\\n        <h2 style={{ fontSize: \\\"0.8em\\\" }}>WATCH</h2>\\n        <h1 style={{ fontSize: props.titleFontSize }}>{props.title}</h1>\\n      </div>\\n    </div>\\n  )\\n\\n  render() {\\n    return (\\n      <div\\n        key={this.props.postId}\\n        style={{\\n          width: this.props.width,\\n          height: \\\"50%\\\",\\n        }}\\n        className=\\\"featured-community-video-container\\\"\\n      >\\n        <Link to={routeCodes.POST_DETAILS(this.props.postId)}>\\n          {this.renderVideo(this.props)}\\n        </Link>\\n      </div>\\n    )\\n  }\\n}\\n\\n    \",\n",
        "        \"tags\": [\n",
        "            \"javascript\",\n",
        "            \"reactjs\",\n",
        "            \"image\",\n",
        "            \"youtube\",\n",
        "            \"onerror\",\n",
        "            \"javascript\",\n",
        "            \"reactjs\",\n",
        "            \"image\",\n",
        "            \"youtube\",\n",
        "            \"onerror\"\n",
        "        ],\n",
        "        \"link\": \"https://stackoverflow.com/questions/52999458/image-onerror-handling-in-react\",\n",
        "        \"score\": \"\\n1        \",\n",
        "        \"creation_date\": \"2018-10-25T23:32:04\",\n",
        "        \"answer_count\": \"1\",\n",
        "        \"comments\": [\n",
        "            \"For some reason, the error is still not triggering. I am getting the 404 errors in the console but the onError method is not firing.\",\n",
        "            \"Strange - just to check, do the values of \",\n",
        "            \" prop match the resource urls that are failing to load in dev console?\",\n",
        "            \"Yeah this is the specific url that is giving me troubles \",\n",
        "            \". As you can see \",\n",
        "            \" works just fine. Maybe there is another way to go about it besides the onError method?\",\n",
        "            \"I think the fact that it returns a 404 and also a default blank image, the DOM doesn't think it's an error.\",\n",
        "            \"That's correct - just updated answer, does this help?\"\n",
        "        ],\n",
        "        \"answers\": [\n",
        "            {\n",
        "                \"body\": \"\\nTo achieve this, I would suggest rendering the <img /> based on the state of your <FeatureVideo/> component.\\n\\nYou could for instance, create an Image object, attempt to load the background  image and by this, reliably determine if the image fails to load. On the images success or failure to load, you would then setState() on your <FeaturedVideo/> component with the appropriate background value which would instead be used to rendering you actual <img/> element:\\n\\nclass FeaturedVideo extends Component<Props> {\\n\\n  componentDidMount() {\\n\\n    if(this.props.background) {\\n\\n      // When component mounts, create an image object and attempt to load background\\n      fetch(this.props.background).then(response => {\\n         if(response.ok) {\\n           // On success, set the background state from background\\n           // prop\\n           this.setState({ background : this.props.background })\\n         } else {        \\n           // On failure to load, set the \\\"default\\\" background state\\n           this.setState({ background : this.props.background.replace(\\\"maxresdefault\\\", \\\"hqdefault\\\") })\\n         }\\n      });\\n    }\\n  }\\n\\n  // Update the function signature to be class method to make state access eaiser\\n  renderVideo(props) {\\n\\n    return <div\\n      style={{\\n        width: \\\"100%\\\",\\n        height: \\\"100%\\\",\\n        backgroundSize: \\\"contain\\\",\\n      }}\\n      className=\\\"featured-community-video\\\">\\n\\n      {/* Update image src to come from state */}\\n\\n      <img src={this.state.background} alt=\\\"\\\" />\\n      <div className=\\\"featured-community-video-title\\\">\\n        <h2 style={{ fontSize: \\\"0.8em\\\" }}>WATCH</h2>\\n        <h1 style={{ fontSize: props.titleFontSize }}>{props.title}</h1>\\n      </div>\\n    </div>\\n  }\\n\\n  render() {\\n    return (\\n      <div\\n        key={this.props.postId}\\n        style={{\\n          width: this.props.width,\\n          height: \\\"50%\\\",\\n        }}\\n        className=\\\"featured-community-video-container\\\"\\n      >\\n        <Link to={routeCodes.POST_DETAILS(this.props.postId)}>\\n          {this.renderVideo(this.props)}\\n        </Link>\\n      </div>\\n    )\\n  }\\n}\\n\\n\\nHope that helps!\\n    \",\n",
        "                \"score\": null\n",
        "            }\n",
        "        ],\n",
        "        \"selected_answer\": \"\\nTo achieve this, I would suggest rendering the <img /> based on the state of your <FeatureVideo/> component.\\n\\nYou could for instance, create an Image object, attempt to load the background  image and by this, reliably determine if the image fails to load. On the images success or failure to load, you would then setState() on your <FeaturedVideo/> component with the appropriate background value which would instead be used to rendering you actual <img/> element:\\n\\nclass FeaturedVideo extends Component<Props> {\\n\\n  componentDidMount() {\\n\\n    if(this.props.background) {\\n\\n      // When component mounts, create an image object and attempt to load background\\n      fetch(this.props.background).then(response => {\\n         if(response.ok) {\\n           // On success, set the background state from background\\n           // prop\\n           this.setState({ background : this.props.background })\\n         } else {        \\n           // On failure to load, set the \\\"default\\\" background state\\n           this.setState({ background : this.props.background.replace(\\\"maxresdefault\\\", \\\"hqdefault\\\") })\\n         }\\n      });\\n    }\\n  }\\n\\n  // Update the function signature to be class method to make state access eaiser\\n  renderVideo(props) {\\n\\n    return <div\\n      style={{\\n        width: \\\"100%\\\",\\n        height: \\\"100%\\\",\\n        backgroundSize: \\\"contain\\\",\\n      }}\\n      className=\\\"featured-community-video\\\">\\n\\n      {/* Update image src to come from state */}\\n\\n      <img src={this.state.background} alt=\\\"\\\" />\\n      <div className=\\\"featured-community-video-title\\\">\\n        <h2 style={{ fontSize: \\\"0.8em\\\" }}>WATCH</h2>\\n        <h1 style={{ fontSize: props.titleFontSize }}>{props.title}</h1>\\n      </div>\\n    </div>\\n  }\\n\\n  render() {\\n    return (\\n      <div\\n        key={this.props.postId}\\n        style={{\\n          width: this.props.width,\\n          height: \\\"50%\\\",\\n        }}\\n        className=\\\"featured-community-video-container\\\"\\n      >\\n        <Link to={routeCodes.POST_DETAILS(this.props.postId)}>\\n          {this.renderVideo(this.props)}\\n        </Link>\\n      </div>\\n    )\\n  }\\n}\\n\\n\\nHope that helps!\\n    \",\n",
        "        \"images\": []\n",
        "    },\n",
        "    {\n",
        "        \"title\": \"Replace broken img with fallback picture\",\n",
        "        \"body\": \"\\n                \\nIt's really simple: if the link to a pic is broken a backup link steps in. I've googled this and it should be straight forward but I can't get it working. I need to add it in Javascript and this is the line I've been trying to fix it with:\\n\\nvar issuePicFront = document.createElement(\\\"img\\\");\\nissuePicFront.id = \\\"first\\\" + count;\\nissuePicFront.src = issues[count].images.imageFront;\\nissuePicFront.onerror=\\\"this.src=replacePic\\\";\\nvar replacePic = https://www.jordans.com/~/media/jordans%20redesign/no-image-found.ashx?h=275&la=en&w=275&hash=F87BC23F17E37D57E2A0B1CC6E2E3EEE312AAD5B\\n\\n\\nI still get 404 (Not found). According to the majority och the internetz this is the common solution but don't work for me.\\n\\nAny clues to solve this?\\n    \",\n",
        "        \"tags\": [\n",
        "            \"javascript\",\n",
        "            \"onerror\",\n",
        "            \"javascript\",\n",
        "            \"onerror\"\n",
        "        ],\n",
        "        \"link\": \"https://stackoverflow.com/questions/50857903/replace-broken-img-with-fallback-picture\",\n",
        "        \"score\": \"\\n-1        \",\n",
        "        \"creation_date\": \"2018-06-14T12:45:46\",\n",
        "        \"answer_count\": \"1\",\n",
        "        \"comments\": [\n",
        "            \"Possible duplicate of \"\n",
        "        ],\n",
        "        \"answers\": [\n",
        "            {\n",
        "                \"body\": \"\\nYou should put quotes around the fallback URL (Assuming the rest of the code is working). \\n\\nI would also suggest to change the error handler to a function, like this:\\n\\nissuePicFront.onerror=function(e){\\n   var replacePic = '<URL>'\\n   this.src=replacePic;\\n};\\n\\n    \",\n",
        "                \"score\": null\n",
        "            }\n",
        "        ],\n",
        "        \"selected_answer\": \"\\nYou should put quotes around the fallback URL (Assuming the rest of the code is working). \\n\\nI would also suggest to change the error handler to a function, like this:\\n\\nissuePicFront.onerror=function(e){\\n   var replacePic = '<URL>'\\n   this.src=replacePic;\\n};\\n\\n    \",\n",
        "        \"images\": []\n",
        "    },\n",
        "    {\n",
        "        \"title\": \"\\\"Script Error.\\\" errors in window.onerror in Safari only\",\n",
        "        \"body\": \"\\n                \\nI'm getting \\\"Script Error.\\\" when catching errors in window.onerror, even with properly (I think) configured CORS headers on S3.\\n\\nCORS config:\\n\\n<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\\n<CORSConfiguration xmlns=\\\"http://s3.amazonaws.com/doc/2006-03-01/\\\">\\n<CORSRule>\\n    <AllowedOrigin>*</AllowedOrigin>\\n    <AllowedMethod>GET</AllowedMethod>\\n    <AllowedMethod>POST</AllowedMethod>\\n    <AllowedMethod>PUT</AllowedMethod>\\n    <AllowedMethod>HEAD</AllowedMethod>\\n    <MaxAgeSeconds>3000</MaxAgeSeconds>\\n    <AllowedHeader>*</AllowedHeader>\\n</CORSRule>\\n</CORSConfiguration>\\n\\n\\nHTML:\\n\\n<script crossorigin src=\\\"https://s3.amazonaws.com/safari-script-error/foo.js\\\" />\\n\\n\\nwhich contains:\\n\\nwindow.addEventListener(\\\"keydown\\\", function(event) {\\n  if (event.keyCode === 69) { // \\\"e\\\" button\\n    throw new Error(\\\"Oh shoot\\\");\\n  }\\n});\\n\\n\\nJS:\\n\\nwindow.onerror = function(event) {\\n  console.log(event);\\n}\\n\\n\\nCodepen: https://codepen.io/astashov/pen/yoEvRB\\n\\nIt works fine in Chrome, Firefox and IE11, and only shows \\\"Script error.\\\" in Safari (I have Version 10.0.3 (12602.4.8)).\\n\\nHow to make it work in Safari too?\\n    \",\n",
        "        \"tags\": [\n",
        "            \"javascript\",\n",
        "            \"html\",\n",
        "            \"safari\",\n",
        "            \"cors\",\n",
        "            \"onerror\",\n",
        "            \"javascript\",\n",
        "            \"html\",\n",
        "            \"safari\",\n",
        "            \"cors\",\n",
        "            \"onerror\"\n",
        "        ],\n",
        "        \"link\": \"https://stackoverflow.com/questions/45844565/script-error-errors-in-window-onerror-in-safari-only\",\n",
        "        \"score\": \"\\n8        \",\n",
        "        \"creation_date\": \"2017-08-23T16:03:40\",\n",
        "        \"answer_count\": \"2\",\n",
        "        \"comments\": [\n",
        "            \"BTW, your \",\n",
        "            \" element cannot be self-closing - I wonder if this could be the cause of the errror?\",\n",
        "            \"No, even if I replace \",\n",
        "            \" with \",\n",
        "            \", it still behaves the same way. Also, \",\n",
        "            \" works just fine for me for the exceptions originated from the same domain in Safari.\"\n",
        "        ],\n",
        "        \"answers\": [\n",
        "            {\n",
        "                \"body\": \"\\n\\nHow to make it work in Safari too?\\n\\nYou can\\u2019t. Current Safari versions don\\u2019t support giving error messages to the onerror callback in the cross-origin case\\u2014even if a crossorigin attribute is specified on the script element.\\nSafari did support it previously, but subsequently regressed at some point.\\nThere\\u2019s an open bug for this at https://bugs.webkit.org/show_bug.cgi?id=132945\\n    \",\n",
        "                \"score\": null\n",
        "            },\n",
        "            {\n",
        "                \"body\": \"\\nIt doesn't appear that CORS is the problem. It appears that support for the global onerror handler isn't in every browser.\\n\\nSee: \\nhttps://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror\\n\\nActually, it probably is related to CORS. \\n\\n\\n  When a syntax(?) error occurs in a script, loaded from a different origin, the details of the syntax error are not reported to prevent leaking information (see bug 363897). Instead the error reported is simply \\\"Script error.\\\" This behavior can be overriden in some browsers using the crossorigin attribute on  and having the server send the appropriate CORS HTTP response headers.  A workaround is to isolate \\\"Script error.\\\" and handle it knowing that the error detail is only viewable in the browser console and not accessible via JavaScript.\\n\\n    \",\n",
        "                \"score\": null\n",
        "            }\n",
        "        ],\n",
        "        \"selected_answer\": \"\\n\\nHow to make it work in Safari too?\\n\\nYou can\\u2019t. Current Safari versions don\\u2019t support giving error messages to the onerror callback in the cross-origin case\\u2014even if a crossorigin attribute is specified on the script element.\\nSafari did support it previously, but subsequently regressed at some point.\\nThere\\u2019s an open bug for this at https://bugs.webkit.org/show_bug.cgi?id=132945\\n    \",\n",
        "        \"images\": []\n",
        "    },\n",
        "    {\n",
        "        \"title\": \"window onerror filter out the addon/extension errors\",\n",
        "        \"body\": \"\\n                \\nI use a simple custom code to catch my js errors from my website. I use a window.onerror handler. However, I see that there are many addon/extension errors that users have installed into their browsers. I don't want to get those. Is there a way to filter those out and get only what is related to my code?\\n    \",\n",
        "        \"tags\": [\n",
        "            \"javascript\",\n",
        "            \"onerror\",\n",
        "            \"javascript\",\n",
        "            \"onerror\"\n",
        "        ],\n",
        "        \"link\": \"https://stackoverflow.com/questions/39558524/window-onerror-filter-out-the-addon-extension-errors\",\n",
        "        \"score\": \"\\n4        \",\n",
        "        \"creation_date\": \"2016-09-18T14:09:55\",\n",
        "        \"answer_count\": \"4\",\n",
        "        \"comments\": [\n",
        "            \"That sounds correct, though I'm no specialist. I'm wondering if Chrome's extension would even throw in the main window given they're only in SW or in popup, so the issue might be moot there, except if OP wants to capture injected scripts, in which case the stack trick wouldn't work.\",\n",
        "            \"I found a better solution and updated the answer. Stack trace includes the URL to the script so you can filter with it and in my testing, this works in all browsers.\",\n",
        "            \"But then they'll lose the errors thrown from external scripts\",\n",
        "            \"3rd-party scripts can be filtered via their origin as well, but I'll leave that as an exercise to the user.\",\n",
        "            \"Some non-extension errors may have no error/stack (for example CORS errors when you do \",\n",
        "            \"), so this solution may filter out more than you would want.\",\n",
        "            \"The question is not about how to log errors, the question is about how to filter out rubbish errors coming from extensions while logging.\"\n",
        "        ],\n",
        "        \"answers\": [\n",
        "            {\n",
        "                \"body\": \"\\nI don't know if this would work, but as mdn, there is a property in the ErrorEvent, the ErrorEvent is defined in here :\\naddEventListener(\\\"error\\\",function(err){\\nconsole.log(err) //Here it is your error, ErrorEvent\\n})\\n\\nNow, when you know the name of the javascript file, you can use the file, so you can filter the errors by file names :\\nerr.filename\\n\\nand if you are looking for chrome extensions, maybe it is near to impossible, as the chrome extensions are a part of the UI and therefore, a part of the window object\\n    \",\n",
        "                \"score\": null\n",
        "            },\n",
        "            {\n",
        "                \"body\": \"\\nFrom docs http://www.w3schools.com/js/js_window.asp\\n\\nThe window object is supported by all browsers. It represents the browser's window.\\nAll global JavaScript objects, functions, and variables automatically become members of the window object.\\nGlobal variables are properties of the window object.\\nGlobal functions are methods of the window object.\\nEven the document object (of the HTML DOM) is a property of the window object.\\n\\nSo that's why addons error appears in your catch block. \\n\\nBut from this.\\n\\nhttps://developer.mozilla.org/en/docs/Web/API/GlobalEventHandlers/onerror \\n\\nI would suggest you inside onError handler check messages and sources to see if this error corresponds to your code. If not just ignore it.\\n\\nHope this helps.\\n    \",\n",
        "                \"score\": null\n",
        "            },\n",
        "            {\n",
        "                \"body\": \"\\ne.stack includes URLs to the triggering script, so with that you can filter only for first-party scripts. Keep note that e.stack is non-standard, but widely supported.\\nwindow.addEventListener('error', e => {\\n  if (e.error?.stack?.includes(window.location.origin)) {\\n    // handle first-party error\\n  }\\n});\\nwindow.addEventListener('unhandledrejection', e => {\\n  if (e.reason?.stack?.includes(window.location.origin)) {\\n    // handle first-party error\\n  }\\n});\\n\\n    \",\n",
        "                \"score\": null\n",
        "            },\n",
        "            {\n",
        "                \"body\": \"\\nJust use event listeners like this:\\nwindow.addEventListener('error', (e) => {\\n    console.log(e);\\n});\\n\\nEvent handlers (like window.onerror) are only useful for ancient browsers.\\n    \",\n",
        "                \"score\": null\n",
        "            }\n",
        "        ],\n",
        "        \"selected_answer\": null,\n",
        "        \"images\": []\n",
        "    },\n",
        "    {\n",
        "        \"title\": \"Is it possible to override native fetch api to use a desired Promise library instead of native browser Promise?\",\n",
        "        \"body\": \"\\n                \\nHere is what I mean.\\n\\nIf the browser natively supports fetch api (for example, Chrome), then it uses the native browser Promise.\\n\\nIf I use another Promise library, (like bluebird, for example), native fetch still isn't using it \\u2014 it uses native Promise implementation instead.\\n\\nIs there a way to override that?\\n\\nProblem example:\\n\\nwindow.Promise = function () { return null; };\\n\\n\\nfetch('/api')\\n.then(function (res) {\\n    console.log('fetch result!', res); // still works because it uses native Promise\\n});\\n\\n\\nWhy would I need that, you may be wondering? I wish to make use global rejection events which bluebird library supports and native Promises don't have.\\n    \",\n",
        "        \"tags\": [\n",
        "            \"javascript\",\n",
        "            \"error-handling\",\n",
        "            \"es6-promise\",\n",
        "            \"onerror\",\n",
        "            \"fetch-api\",\n",
        "            \"javascript\",\n",
        "            \"error-handling\",\n",
        "            \"es6-promise\",\n",
        "            \"onerror\",\n",
        "            \"fetch-api\"\n",
        "        ],\n",
        "        \"link\": \"https://stackoverflow.com/questions/35367266/is-it-possible-to-override-native-fetch-api-to-use-a-desired-promise-library-ins\",\n",
        "        \"score\": \"\\n8        \",\n",
        "        \"creation_date\": \"2016-02-12T16:15:59\",\n",
        "        \"answer_count\": \"3\",\n",
        "        \"comments\": [\n",
        "            \"The browser doesn't care if your using a promise library, it only knows about its own promises. It won't automatically change to a different implementation.\",\n",
        "            \"Excellent! I wrapped the \",\n",
        "            \" call in a function, and used this snippet: \"\n",
        "        ],\n",
        "        \"answers\": [\n",
        "            {\n",
        "                \"body\": \"\\nHere's some code that goes along the same line as @MinusFour suggested. Replace global with window if you're in a browser and not inside a module.\\n\\nconst fetch = global.fetch\\nglobal.fetch = function() {\\n    return Promise.resolve(fetch.apply(global, arguments))\\n}\\n\\n    \",\n",
        "                \"score\": null\n",
        "            },\n",
        "            {\n",
        "                \"body\": \"\\nYou could use bluebird Promise.resolve() on the fetch promise. It will create a bluebird promise that assimilates fetch promise.\\n\\nPromise.resolve(Promise|any value) -> Promise\\n\\nCreate a promise that is resolved with the given value. If value is already a trusted Promise, it is returned as is. If value is not a thenable, a fulfilled Promise is returned with value as its fulfillment value. If value is a thenable (Promise-like object, like those returned by jQuery's $.ajax), returns a trusted Promise that assimilates the state of the thenable.\\n\\n\\nhttp://bluebirdjs.com/docs/api/promise.resolve.html\\n    \",\n",
        "                \"score\": null\n",
        "            },\n",
        "            {\n",
        "                \"body\": \"\\nI found this too and thought it might make sense to post it here -\\nhttps://github.com/github/fetch/issues/417\\n\\nThe post says (in case the link in broken) - \\nif you want to use bluebird in browser, use this, and\\n\\n\\n  window.fetch = null\\n  \\n  window.Promise = bluebird\\n  \\n  require('whatwg-fetch') the latest version browser may have fetch API\\n  already, this repo will return false if there is fetch API.\\n  \\n  if you want to use bluebird in node, use node-fetch, and\\n  \\n  let fetch = require('node-fetch');\\n  \\n  fetch.Promise = bluebird\\n\\n    \",\n",
        "                \"score\": null\n",
        "            }\n",
        "        ],\n",
        "        \"selected_answer\": null,\n",
        "        \"images\": []\n",
        "    },\n",
        "    {\n",
        "        \"title\": \"On Error GoTo only working once for analyzing input box value\",\n",
        "        \"body\": \"\\n                \\nI have a spreadsheet that tracks the time various files are sent.  For each file I have an input box that asks for the time the file sent, and there are a few other options that can be put in that input box.  \\n\\nIf the person does not enter a valid entry, I would like to send them back to the input box so they can try again.  \\n\\nThis is my code, which works for the first error, but if someone enters the wrong value a second time, they just get the standard 'Type Mismatch' error.  I am creating this for people who don't have any knowledge of VBA and would like to make it as easy as possible.  \\n\\nThere are multiple instances of the following code, each for a different file time.  Thanks in advance!\\n\\nCFP:\\nIf Err Then MsgBox Error & \\\" Invalid value.  Please enter only 'blank', 'holiday', 'skip' or time value.\\\"\\nErr.Clear\\ntm = UCase(Application.InputBox(\\\"What time was the CFP file sent?\\\"))\\n\\nOn Error GoTo CFP\\nIf tm = \\\"BLANK\\\" Then\\n    ActiveCell.Value = \\\"Blank\\\"\\nElseIf tm = \\\"HOLIDAY\\\" Then\\n    ActiveCell.Value = \\\"Holiday\\\"\\nElseIf tm = \\\"SKIP\\\" Then\\n        ActiveCell.Value = \\\"Skipped\\\"\\nElse\\n    ActiveCell.Value = TimeValue(tm)\\nEnd If\\n\\n    \",\n",
        "        \"tags\": [\n",
        "            \"vba\",\n",
        "            \"excel\",\n",
        "            \"onerror\",\n",
        "            \"vba\",\n",
        "            \"excel\",\n",
        "            \"onerror\"\n",
        "        ],\n",
        "        \"link\": \"https://stackoverflow.com/questions/29951610/on-error-goto-only-working-once-for-analyzing-input-box-value\",\n",
        "        \"score\": \"\\n2        \",\n",
        "        \"creation_date\": \"2015-04-29T18:24:40\",\n",
        "        \"answer_count\": \"2\",\n",
        "        \"comments\": [\n",
        "            \"This explains perfectly your problem.\",\n",
        "            \"Thank you both!!  I ended up using the error handler, but since I have to do the input box step repeatedly for different files, I decided to pass the name of each file to sub(fileName).  Then the time for that file is entered in an input box and then run through an error handler.  Thanks Again!\"\n",
        "        ],\n",
        "        \"answers\": [\n",
        "            {\n",
        "                \"body\": \"\\nRather than using the error handler, I would use a Loop that would break only when the condition is met. For example: \\n\\nAsk the first time:\\n\\ntm = UCase(Application.InputBox(\\\"What time was the CFP file sent?\\\"))\\nDim inputOK As Boolean\\n\\n\\nKeep on asking until the user enters wrong values:\\n\\ninputOK = checkMyInput(tm) '<-- is the input \\\"tm\\\" ok or not?\\nDo While inputOK = False '<-- if it's not ok, keep on asking\\n    MsgBox \\\"Please enter a valid input\\\"\\n    tm = UCase(Application.InputBox(\\\"What time was the CFP file sent?\\\"))   \\n    inputOK = checkMyInput(tm) '<-- and checking it again...\\nLoop\\n\\n\\nwhere checkMyInput(tm) would be a custom function returning True or False if your input is ok or not:\\n\\nFunction checkMyInput(ByVal tm As Variant) As Boolean\\n    If tm =\\\"BLANK\\\" Or tm = \\\"HOLIDAY\\\" Or tm = \\\"SKIP\\\" Or IsDate(tm) Then\\n        checkMyInput = True\\n    Else\\n        checkMyInput = False\\n    End If\\nEnd Function\\n\\n    \",\n",
        "                \"score\": null\n",
        "            },\n",
        "            {\n",
        "                \"body\": \"\\nError handlers go below the procedure they're handling errors for:\\n\\nPublic Sub DoSomething\\n    On Error GoTo ErrHandler\\n\\n    'code here\\n\\nCleanup:\\n    'cleanup code here\\n    Exit Sub\\n\\nErrHandler:\\n    'error-handling code here\\n    Resume Cleanup\\nEnd Sub\\n\\n\\nWhat's happening is that once the first error is raised, because the error handler label is at the top, instead of jumping down into the error handler, the code jumps up back to the top, and VBA understands the rest of the procedure to be the error-handling subroutine... which never returns to the actual procedure body, because it is the procedure's body.\\n\\nYou're using the wrong control flow structure for the job, see @Matteo's answer for what you need.\\n    \",\n",
        "                \"score\": null\n",
        "            }\n",
        "        ],\n",
        "        \"selected_answer\": \"\\nError handlers go below the procedure they're handling errors for:\\n\\nPublic Sub DoSomething\\n    On Error GoTo ErrHandler\\n\\n    'code here\\n\\nCleanup:\\n    'cleanup code here\\n    Exit Sub\\n\\nErrHandler:\\n    'error-handling code here\\n    Resume Cleanup\\nEnd Sub\\n\\n\\nWhat's happening is that once the first error is raised, because the error handler label is at the top, instead of jumping down into the error handler, the code jumps up back to the top, and VBA understands the rest of the procedure to be the error-handling subroutine... which never returns to the actual procedure body, because it is the procedure's body.\\n\\nYou're using the wrong control flow structure for the job, see @Matteo's answer for what you need.\\n    \",\n",
        "        \"images\": []\n",
        "    },\n",
        "    {\n",
        "        \"title\": \"Return JSONP from OnError Pipeline using NancyFX\",\n",
        "        \"body\": \"\\n                \\nI've got a simple API that is returning JSON.\\nThere is a use case for certain clients to require a JSONP response.\\n\\nNancy returns JSONP naturally if you provide a callback parameter (super happy awesome!).\\n\\nUnfortunately, when I'm trying to handle exceptions, I'm just getting JSON back when I return a Nancy response.\\nSeems like the JSONP functionality is only baked into the AfterRequest pipeline?\\n\\nMy error handling:\\n\\npublic class ErrorHandlingStartup : IApplicationStartup\\n{\\n    public void Initialize(IPipelines pipelines)\\n    {\\n        pipelines.OnError.AddItemToEndOfPipeline((ctx, exception) =>\\n        {\\n            var response = ErrorResponse.FromException(exception);\\n\\n            return response;\\n        });\\n    }\\n}\\n\\n\\nThe nancy JsonP class:\\nhttps://github.com/NancyFx/Nancy/blob/master/src/Nancy/Jsonp.cs\\n\\nIs there anything simple that I'm missing or do I need implement the JsonP functionality to also cover OnError?\\n    \",\n",
        "        \"tags\": [\n",
        "            \"asp.net\",\n",
        "            \"api\",\n",
        "            \"jsonp\",\n",
        "            \"nancy\",\n",
        "            \"onerror\",\n",
        "            \"asp.net\",\n",
        "            \"api\",\n",
        "            \"jsonp\",\n",
        "            \"nancy\",\n",
        "            \"onerror\"\n",
        "        ],\n",
        "        \"link\": \"https://stackoverflow.com/questions/27845582/return-jsonp-from-onerror-pipeline-using-nancyfx\",\n",
        "        \"score\": \"\\n1        \",\n",
        "        \"creation_date\": \"2015-01-08T17:01:56\",\n",
        "        \"answer_count\": \"0\",\n",
        "        \"comments\": [],\n",
        "        \"answers\": [],\n",
        "        \"selected_answer\": null,\n",
        "        \"images\": []\n",
        "    },\n",
        "    {\n",
        "        \"title\": \"Changing an image src on the fly with Javascript\",\n",
        "        \"body\": \"\\n                \\nI'm trying to change the src of some img tags if/when there is a problem with the pics when loading the page.  I seem to be getting some random behavior particularly from Internet Explorer 9.  Some of the images show the replaced image correctly and some have a red cross on them.  If I debug in the browser I'm told that ImgError() is not defined.  It's clearly defined in the code and is obviously working.  Why is this happening?\\n\\n<div class=\\\"PhotoBorder\\\"><img alt=\\\"\\\" onerror=\\\"imgError(this)\\\" \\n    src=\\\"./images/services/69_Staffmember.jpg\\\" /></div>\\n\\n<script src=\\\"https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js\\\">           \\n    </script>  \\n\\n<script> \\n$(window).load( function() {\\n    $('.RowWrapper').each(function() {\\n        var TotalWidth = 0;\\n        $(this).find('.StaffMember').each(function() {\\n            TotalWidth = TotalWidth + $(this).outerWidth(true);     \\n        });\\n        this.style.width = TotalWidth + \\\"px\\\";           \\n    });\\n});\\n\\nfunction imgError(img)\\n{ \\n    img.setAttribute(\\\"src\\\",\\\"./images/services/49_ImgMissing.jpg\\\");  \\n    img.removeAttribute(\\\"onerror\\\");\\n}     \\n\\n</script>\\n\\n    \",\n",
        "        \"tags\": [\n",
        "            \"javascript\",\n",
        "            \"html\",\n",
        "            \"image\",\n",
        "            \"onerror\",\n",
        "            \"javascript\",\n",
        "            \"html\",\n",
        "            \"image\",\n",
        "            \"onerror\"\n",
        "        ],\n",
        "        \"link\": \"https://stackoverflow.com/questions/22752133/changing-an-image-src-on-the-fly-with-javascript\",\n",
        "        \"score\": \"\\n1        \",\n",
        "        \"creation_date\": \"2014-03-31T01:09:35\",\n",
        "        \"answer_count\": \"3\",\n",
        "        \"comments\": [\n",
        "            \"TotalWidth.toString() + \\\"px\\\";\",\n",
        "            \"The script defining \",\n",
        "            \" must be \",\n",
        "            \" any code that calls it. HTML is parsed and \\\"executed\\\" sequentially.\",\n",
        "            \"What does this have to do with jQuery?\",\n",
        "            \"@RobG  Your suggestion seemed to work.  Please submit an answer and I will mark as correct.\",\n",
        "            \"Yes that was just a typo in the question.\",\n",
        "            \"Wow, seriously?  I am using a content management system.  I don't have access to the head section of the page.\",\n",
        "            \"Isn't that the whole point of document.ready or even window.load??  The document is supposed to be ready to work on.\",\n",
        "            \"@PaulMatthews - what part of your code has anything to do with \",\n",
        "            \"? the onerror attribute fires when there's an error requesting the image. That may be immediately or after a delay. Additionally, your \",\n",
        "            \" function isn't inside any \",\n",
        "            \" (not that it would make a difference).\",\n",
        "            \"Can't use IDs because there are many images.  The code is designed to work for each individual one.\",\n",
        "            \"are you using jquery?\",\n",
        "            \"@jp310 I think he is using jQuery based from the script code\",\n",
        "            \"or you can try: $(\\\".your_class\\\").attr(\\\"src\\\",\\\"your_src\\\");\",\n",
        "            \"I use jQuery in my code as you can see but not for this.  I simply use the onError attribute to call the ImgError() function.\"\n",
        "        ],\n",
        "        \"answers\": [\n",
        "            {\n",
        "                \"body\": \"\\nFirstly, if you're getting the error that ImgError() is not defined it's because your function name is imgError, not ImgError(). \\n\\nBut, if that was a typo in your question then it's possible that you're getting the error imgError() is not defined at some points because chances are the image is being requested from the cache and it's error handler is firing instantaneously - i.e. before the rest of your document has been parsed meaning that your imgError function is not yet available. To fix it, just put your imgError function in a script tag in the head of your document.\\n    \",\n",
        "                \"score\": null\n",
        "            },\n",
        "            {\n",
        "                \"body\": \"\\nGive your image element an id and try this:\\n\\ndocument.getElementById(\\\"imageid\\\").src=\\\"./images/services/49_ImgMissing.jpg\\\";\\n\\n    \",\n",
        "                \"score\": null\n",
        "            },\n",
        "            {\n",
        "                \"body\": \"\\nI'm answering on behalf of RobG.  The definition of imgError() was below where it was being called in my code.  You must position your code definitions above where you make calls in your html.  Otherwise your results may be undefined as I found out.\\n    \",\n",
        "                \"score\": null\n",
        "            }\n",
        "        ],\n",
        "        \"selected_answer\": \"\\nI'm answering on behalf of RobG.  The definition of imgError() was below where it was being called in my code.  You must position your code definitions above where you make calls in your html.  Otherwise your results may be undefined as I found out.\\n    \",\n",
        "        \"images\": []\n",
        "    }\n",
        "]"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "! pip install torch sentence-transformers faiss-cpu tqdm numpy"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "cCVLrEid0BGW",
        "outputId": "535c7cba-7f0f-40e8-ab2d-5ce5a225333c"
      },
      "execution_count": 2,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: torch in /usr/local/lib/python3.11/dist-packages (2.5.1+cu124)\n",
            "Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.11/dist-packages (3.4.1)\n",
            "Collecting faiss-cpu\n",
            "  Downloading faiss_cpu-1.10.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (4.4 kB)\n",
            "Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (4.67.1)\n",
            "Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (1.26.4)\n",
            "Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch) (3.17.0)\n",
            "Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.11/dist-packages (from torch) (4.12.2)\n",
            "Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch) (3.4.2)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch) (3.1.5)\n",
            "Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch) (2024.10.0)\n",
            "Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch)\n",
            "  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)\n",
            "Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch)\n",
            "  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)\n",
            "Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch)\n",
            "  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)\n",
            "Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch)\n",
            "  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)\n",
            "Collecting nvidia-cublas-cu12==12.4.5.8 (from torch)\n",
            "  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)\n",
            "Collecting nvidia-cufft-cu12==11.2.1.3 (from torch)\n",
            "  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)\n",
            "Collecting nvidia-curand-cu12==10.3.5.147 (from torch)\n",
            "  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)\n",
            "Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch)\n",
            "  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)\n",
            "Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch)\n",
            "  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)\n",
            "Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch) (2.21.5)\n",
            "Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.127)\n",
            "Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch)\n",
            "  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)\n",
            "Requirement already satisfied: triton==3.1.0 in /usr/local/lib/python3.11/dist-packages (from torch) (3.1.0)\n",
            "Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch) (1.13.1)\n",
            "Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch) (1.3.0)\n",
            "Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (4.48.3)\n",
            "Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (1.6.1)\n",
            "Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (1.13.1)\n",
            "Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (0.28.1)\n",
            "Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (11.1.0)\n",
            "Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from faiss-cpu) (24.2)\n",
            "Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.2)\n",
            "Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.3)\n",
            "Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2024.11.6)\n",
            "Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.21.0)\n",
            "Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.5.3)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch) (3.0.2)\n",
            "Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers) (1.4.2)\n",
            "Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers) (3.5.0)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.4.1)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.10)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.3.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2025.1.31)\n",
            "Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m363.4/363.4 MB\u001b[0m \u001b[31m4.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m13.8/13.8 MB\u001b[0m \u001b[31m40.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m24.6/24.6 MB\u001b[0m \u001b[31m31.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m883.7/883.7 kB\u001b[0m \u001b[31m47.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m664.8/664.8 MB\u001b[0m \u001b[31m2.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m211.5/211.5 MB\u001b[0m \u001b[31m6.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m56.3/56.3 MB\u001b[0m \u001b[31m12.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m127.9/127.9 MB\u001b[0m \u001b[31m7.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m207.5/207.5 MB\u001b[0m \u001b[31m5.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m21.1/21.1 MB\u001b[0m \u001b[31m82.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading faiss_cpu-1.10.0-cp311-cp311-manylinux_2_28_x86_64.whl (30.7 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m30.7/30.7 MB\u001b[0m \u001b[31m67.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hInstalling collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, faiss-cpu, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12\n",
            "  Attempting uninstall: nvidia-nvjitlink-cu12\n",
            "    Found existing installation: nvidia-nvjitlink-cu12 12.5.82\n",
            "    Uninstalling nvidia-nvjitlink-cu12-12.5.82:\n",
            "      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82\n",
            "  Attempting uninstall: nvidia-curand-cu12\n",
            "    Found existing installation: nvidia-curand-cu12 10.3.6.82\n",
            "    Uninstalling nvidia-curand-cu12-10.3.6.82:\n",
            "      Successfully uninstalled nvidia-curand-cu12-10.3.6.82\n",
            "  Attempting uninstall: nvidia-cufft-cu12\n",
            "    Found existing installation: nvidia-cufft-cu12 11.2.3.61\n",
            "    Uninstalling nvidia-cufft-cu12-11.2.3.61:\n",
            "      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61\n",
            "  Attempting uninstall: nvidia-cuda-runtime-cu12\n",
            "    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82\n",
            "    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:\n",
            "      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82\n",
            "  Attempting uninstall: nvidia-cuda-nvrtc-cu12\n",
            "    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82\n",
            "    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:\n",
            "      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82\n",
            "  Attempting uninstall: nvidia-cuda-cupti-cu12\n",
            "    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82\n",
            "    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:\n",
            "      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82\n",
            "  Attempting uninstall: nvidia-cublas-cu12\n",
            "    Found existing installation: nvidia-cublas-cu12 12.5.3.2\n",
            "    Uninstalling nvidia-cublas-cu12-12.5.3.2:\n",
            "      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2\n",
            "  Attempting uninstall: nvidia-cusparse-cu12\n",
            "    Found existing installation: nvidia-cusparse-cu12 12.5.1.3\n",
            "    Uninstalling nvidia-cusparse-cu12-12.5.1.3:\n",
            "      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3\n",
            "  Attempting uninstall: nvidia-cudnn-cu12\n",
            "    Found existing installation: nvidia-cudnn-cu12 9.3.0.75\n",
            "    Uninstalling nvidia-cudnn-cu12-9.3.0.75:\n",
            "      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75\n",
            "  Attempting uninstall: nvidia-cusolver-cu12\n",
            "    Found existing installation: nvidia-cusolver-cu12 11.6.3.83\n",
            "    Uninstalling nvidia-cusolver-cu12-11.6.3.83:\n",
            "      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83\n",
            "Successfully installed faiss-cpu-1.10.0 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import json\n",
        "import torch\n",
        "import numpy as np\n",
        "import faiss\n",
        "from tqdm import tqdm\n",
        "from transformers import BertTokenizer, BertModel\n",
        "\n",
        "# add our json file paths\n",
        "JSON_FILES = [\n",
        "    \"sample.json\"\n",
        "]\n",
        "\n",
        "# out\n",
        "EMBEDDING_FILE = \"stackoverflow_bert_embeddings.npy\"\n",
        "METADATA_FILE = \"stackoverflow_bert_metadata.json\"\n",
        "\n",
        "\n",
        "MODEL_NAME = \"bert-base-uncased\"\n",
        "BATCH_SIZE = 8  # increase it to occupy the gpu for faster inference\n",
        "MAX_TOKENS = 512  # max tokens\n",
        "DEVICE = \"cuda\" if torch.cuda.is_available() else \"cpu\"\n",
        "\n",
        "\n",
        "tokenizer = BertTokenizer.from_pretrained(MODEL_NAME)\n",
        "model = BertModel.from_pretrained(MODEL_NAME).to(DEVICE)\n",
        "model.eval()\n",
        "\n",
        "\n",
        "def load_questions_from_json(files):\n",
        "    all_questions, metadata = [], []\n",
        "\n",
        "    for file in tqdm(files, desc=\"reading JSON files\"):\n",
        "        with open(file, \"r\", encoding=\"utf-8\") as f:\n",
        "            data = json.load(f)\n",
        "            for item in data:\n",
        "                title = item.get(\"title\", \"\").strip()\n",
        "                body = item.get(\"body\", \"\").strip()\n",
        "                answers = item.get(\"answers\", \"\")\n",
        "                text = f\"{title} {body}\"\n",
        "                all_questions.append(text)\n",
        "                metadata.append({\"title\": title, \"body\": body, \"answers\": answers, \"link\": item.get(\"link\", \"\"), \"tags\": item.get(\"tags\", [])})\n",
        "\n",
        "    return all_questions, metadata\n",
        "\n",
        "\n",
        "questions, metadata = load_questions_from_json(JSON_FILES)\n",
        "\n",
        "\n",
        "def generate_embeddings(text_list, batch_size):\n",
        "    \"\"\"Generates embeddings using PyTorch's transformers on GPU with a configurable batch size.\"\"\"\n",
        "    all_embeddings = []\n",
        "\n",
        "    with torch.no_grad():\n",
        "        for i in tqdm(range(0, len(text_list), batch_size), desc=\"Generating BERT Embeddings on GPU\"):\n",
        "            batch_texts = text_list[i:i+batch_size]\n",
        "\n",
        "            inputs = tokenizer(batch_texts, padding=True, truncation=True, max_length=MAX_TOKENS, return_tensors=\"pt\").to(DEVICE)\n",
        "\n",
        "\n",
        "            outputs = model(**inputs)\n",
        "\n",
        "            # use [CLS] token representation\n",
        "            embeddings = outputs.last_hidden_state[:, 0, :].cpu().numpy()\n",
        "\n",
        "            all_embeddings.append(embeddings)\n",
        "\n",
        "    return np.vstack(all_embeddings)\n",
        "\n",
        "# generate embeddings (on GPU)\n",
        "embeddings = generate_embeddings(questions, BATCH_SIZE)\n",
        "\n",
        "# save embeddings and metadata\n",
        "np.save(EMBEDDING_FILE, embeddings)\n",
        "with open(METADATA_FILE, \"w\", encoding=\"utf-8\") as f:\n",
        "    json.dump(metadata, f, indent=4)\n",
        "\n",
        "print(f\"✅ Saved {embeddings.shape[0]} embeddings to {EMBEDDING_FILE}\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "0hpf0GXI9r7G",
        "outputId": "f078656a-24bf-4d65-e4bf-822d27e12173"
      },
      "execution_count": 15,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "reading JSON files: 100%|██████████| 1/1 [00:00<00:00, 1066.17it/s]\n",
            "Generating BERT Embeddings on GPU: 100%|██████████| 2/2 [00:00<00:00,  4.92it/s]"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "✅ Saved 13 embeddings to stackoverflow_bert_embeddings.npy\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "embeddings.shape"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "rsRb_m0FDGLS",
        "outputId": "2f571a98-6ca6-4681-d173-ad8b0a609740"
      },
      "execution_count": 16,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "(13, 768)"
            ]
          },
          "metadata": {},
          "execution_count": 16
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "len(metadata)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "or91xS8iDq2S",
        "outputId": "5e156a04-6804-458e-f0b8-2ce5be02e509"
      },
      "execution_count": 17,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "13"
            ]
          },
          "metadata": {},
          "execution_count": 17
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "metadata"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Y5MDr8fTDtVP",
        "outputId": "41b47d00-b557-4c39-988a-8570916c93fd"
      },
      "execution_count": 18,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "[{'title': 'Issue with Time Configuration in xlreporter',\n",
              "  'body': \"I'm experiencing issues with xlreporter when graphing data from an SQL query. In my SQL query, I select and filter data using the following query:\\nSELECT PT102_PV, t_stamp FROM group_table WHERE t_stamp BETWEEN '2024-07-30 00:00' AND '2024-07-31 00:00' AND PT102_PV IS NOT NULL ORDER BY t_stamp DESC;\\nIn the SQL query, the date and time are displayed correctly. However, when I configure xlreporter to plot PT102_PV based on the date and time from t_stamp, the time is not being interpreted correctly. The date is correct, but the time appears to be incorrect or misinterpreted. I have checked that xlreporter is set to use the date and time from t_stamp, but the issue persists.\\nHas anyone experienced a similar issue or have suggestions on how to resolve this?\\nI reviewed the configuration in xlreporter and ensured that the date and time format matches that of my SQL query. I also tried different settings in xlreport to adjust the format of the graph axes and make sure the time is interpreted correctly. However, the time still appears incorrectly on the graphs, while the date is displayed correctly.\\nI expected xlreporter to correctly interpret both the date and time from t_stamp and for the graph to accurately reflect these data, showing the correct time for each PT102_PV value.\\ncomparative image SQL query and XLreporter query (SQL Correct)\\nXLReport Configuration\",\n",
              "  'answers': [],\n",
              "  'link': 'https://stackoverflow.com/questions/78836459/issue-with-time-configuration-in-xlreporter',\n",
              "  'tags': ['datetime',\n",
              "   'reporting-services',\n",
              "   'visualization',\n",
              "   'reporting',\n",
              "   'error-reporting',\n",
              "   'datetime',\n",
              "   'reporting-services',\n",
              "   'visualization',\n",
              "   'reporting',\n",
              "   'error-reporting']},\n",
              " {'title': 'How to display an image(as error) instead of error message',\n",
              "  'body': 'const FALLBACK_IMAGE = \"https://devprojectupload.s3.ap-south-1.amazonaws.com/32490.png\";\\n\\n\\nconst ModelComponent = (props) => {\\n\\n  const [height, setHeight] = useState(window.innerHeight);\\n  const [width, setWidth] = useState(window.innerWidth);\\n  \\n  //API data \\n  const [modelData, setModelData] = useState([]);\\n  \\n  //Error\\n  const [isError, setIsError] = useState(\"\");\\n\\n\\nuseEffect(() => {\\naxios.\\nget(\"https://51fgc922b7.execute-api.ap-south-1.amazonaws.com/dev/productpreview\")\\n.then((res) => {\\nconsole.log(res.data.data)\\nsetModelData(res.data.data[0])\\n})\\n.catch((error)=>\\nsetIsError(()=>{\\n, error\\n})\\n)\\n}, []);',\n",
              "  'answers': [{'body': '\\nCurrently you\\'re not returning anything in your setIsError function. You can return the error you receive from the catch or just set it to true\\nsetIsError(()=>{\\n  return error;\\n  // return true;\\n})\\n\\nIn the return of your component you could do something like this, where you check if there is an error and if there is you display your img\\nreturn (\\n  ...\\n  {isError && <img src={FALLBACK_IMAGE} alt=\"error\"/>}\\n  ...\\n);\\n\\n    ',\n",
              "    'score': None}],\n",
              "  'link': 'https://stackoverflow.com/questions/74327725/how-to-display-an-imageas-error-instead-of-error-message',\n",
              "  'tags': ['reactjs', 'onerror', 'reactjs', 'onerror']},\n",
              " {'title': 'nuxtjs vuejs @error is not firing in a component when trying to load a fallback image',\n",
              "  'body': 'I have a component that I feed with props.\\nWhen an image throws a 404 I want to load a fallback image. So far so good.\\nHowever the @error function never fires when an image is broken and I can\\'t figure out why! I never get \\'hello event\\' in the console.\\nThe component is on the first level of a nuxt page, my setup is a static SPA.\\nI tried to implement it as mentioned at the end of this github issue: https://github.com/vuejs/vue/issues/5404\\n<template>\\n  <div class=\"channel\">\\n     <div class=\"img\">\\n       <img :src=\"imgUrl\" :alt=\"name\" :title=\"name\" @error=\"getFallBackImage\" />\\n     </div>\\n  </div>\\n</template>\\n\\n<script>\\n  export default {\\n    data: function() {\\n      return {\\n        chanCover: this.cover\\n      }\\n    },\\n    props: {\\n      name: {\\n        type: String,\\n        required: true\\n      },\\n      cover: {\\n        type: String,\\n        required: true\\n      }\\n    },\\n    computed: {\\n      imgUrl() {\\n        console.log(this.chanCover)\\n        return \"channels/\"+this.chanCover+\".jpg\"\\n      },\\n    },\\n    methods: {\\n      getFallBackImage(event) {\\n        console.log(\"hello event\")\\n        this.chanCover = \"default\"\\n      }\\n    }\\n  }\\n</script>',\n",
              "  'answers': [],\n",
              "  'link': 'https://stackoverflow.com/questions/71610447/nuxtjs-vuejs-error-is-not-firing-in-a-component-when-trying-to-load-a-fallback',\n",
              "  'tags': ['javascript',\n",
              "   'vue.js',\n",
              "   'nuxt.js',\n",
              "   'onerror',\n",
              "   'javascript',\n",
              "   'vue.js',\n",
              "   'nuxt.js',\n",
              "   'onerror']},\n",
              " {'title': 'onerror javascript loads just once?',\n",
              "  'body': 'I\\'ve been trying to figure out the way for loading screen on/off as I choose (not by automatical event).\\nso I came up with this solution:\\ncss:\\n#loading {\\n    display: block;\\n    position: absolute;\\n    top: 0;\\n    left: 0;\\n    z-index: 100;\\n    width: 100vw;\\n    height: 100vh;\\n    background-color: rgba(192, 192, 192, 0.5);\\n    background-image: url(\"https://i.sstatic.net/MnyxU.gif\");\\n    background-repeat: no-repeat;\\n    background-position: center;\\n}\\n\\njavascript:\\nfunction loading(action) {\\n    console.log(action);\\n    document.getElementById(\\'loading\\').style.display = action ? \\'block\\' : \\'none\\';\\n}\\n\\nhtml:\\n<div id=loading></div>\\n<img onerror=\"loading(true)\">\\n// do whatever i need, which takes several seconds to load\\n<img onerror=\"loading(false)\">\\n\\nthe loading screen comes on as suppose to, with no problem whatsoever, however there are two things which are not clear to me...\\n\\nthe console.log(action) does not work... it just won\\'t print anything to console whatsoever\\nsecond image won\\'t turn off the loading screen... it just stays on all the time\\n\\nwhat do I do wrong here?',\n",
              "  'answers': [{'body': '\\nAccording to @Aioros answer, it was partialy correct...\\nafter adding src to both  tags, then it tries to trigger the javascript function, however i was gettig error: loading is not a function which makes no sence to me.\\nso i have replaced:\\n<img src=blabla onerror=\"loading(true/false)\">\\n\\nwith:\\n<script>loading(true/false)</script>\\n\\nand it works just fine now...\\n    ',\n",
              "    'score': None}],\n",
              "  'link': 'https://stackoverflow.com/questions/64268489/onerror-javascript-loads-just-once',\n",
              "  'tags': ['javascript', 'html', 'onerror', 'javascript', 'html', 'onerror']},\n",
              " {'title': 'Is there anyway to catch sandbox Uncaught/Unsafe error messages from cross-origin scripts',\n",
              "  'body': 'When adding an on error event listener, typically you will receive an ErrorEvent object full of details (message, line, column, etc) about the error message; however, when an error is thrown from a cross origin script, all you get is the \"Script error.\" message. From my understanding, this is done for security reasons.\\n\\nI am running into some problems because of this restriction. I have am running cross-origin scripts (not my scripts, they could come from anywhere, I don\\'t control them, total randomness here) within an IFrame element where I have added an on error event listener and the \"sandbox\" attribute.\\n\\nMy goal was to report and sandbox violations that happened to the top level page. So for example, if the sandbox doesn\\'t allow pop-ups. Within the console window an error message is displayed that says something like \"Pops are not allowed in a sandboxed environment\". The onerror picks up on the error, but when you inspect the message, it always says \"Script error\".\\n\\nIs there a different way for me to catch these uncaught/unsafe error messages?\\n\\nMy goal is to parse out the messages to see which sandbox violations are being thrown for logging. This method will not work, because any uncaught error message within the IFrame will get translated to the same message, which could lead to false positives. For example, someone does throw new Error(\\'test\\') and now there is no way for me to tell if it was a sandbox error or a script error.',\n",
              "  'answers': [{'body': '\\nIf the Javascript error message is \"Script error.\", there is no way to extract the actual error message via Javascript. While the user can examine their browser console to see the error details, the cross-origin error details will not be exposed to your Javascript in any way, for security reasons.\\n\\nTo mitigate this, if at all possible, suggest that users use libraries from sites which do not have CORS restrictions. A site that hosts a library needs to have both\\n\\naccess-control-allow-origin: *\\naccess-control-expose-headers: *\\n\\n\\nin order to catch errors thrown in scripts hosted by that site. For example:\\n\\n<script src=\"https://cdn.jsdelivr.net/npm/[email\\xa0protected]/babel.min.js\"></script>\\n\\n\\nBecause jsdelivr has both of those headers, errors thrown will be viewable. (Forgive the stack snippet hacks, but it demonstrates the issue:)\\n\\n\\r\\n\\r\\n-->\\r\\n</style>\\r\\n<script src=\"https://cdn.jsdelivr.net/npm/[email\\xa0protected]/babel.min.js\"></script>\\r\\n</script>\\r\\n</head>\\r\\n<body>\\r\\n<script src=\"/scripts/snippet-javascript-console.min.js?v=1\"></script>\\r\\n<script type=\"text/babel\">Invalid syntax\\r\\n</style>\\r\\n<!--\\r\\n\\r\\n\\r\\n\\n\\nIf the library comes from a site without both of those headers, the error will be opaque. For example, this snippet is identical to the above, except that the link is to a site without access-control-expose-headers: *:\\n\\n\\r\\n\\r\\n-->\\r\\n</style>\\r\\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.10.3/babel.min.js\"></script>\\r\\n</script>\\r\\n</head>\\r\\n<body>\\r\\n<script src=\"/scripts/snippet-javascript-console.min.js?v=1\"></script>\\r\\n<script type=\"text/babel\">Invalid syntax\\r\\n</style>\\r\\n<!--\\r\\n\\r\\n\\r\\n\\n\\nIf you have no control at all over which library links the users use, there\\'s nothing you can do to get access to the opaque errors, unless you can get them to install a custom browser extension (which has escalated privileges), or something like that.\\n    ',\n",
              "    'score': None}],\n",
              "  'link': 'https://stackoverflow.com/questions/55793495/is-there-anyway-to-catch-sandbox-uncaught-unsafe-error-messages-from-cross-origi',\n",
              "  'tags': ['javascript',\n",
              "   'sandbox',\n",
              "   'onerror',\n",
              "   'javascript',\n",
              "   'sandbox',\n",
              "   'onerror']},\n",
              " {'title': 'Image onError Handling in React',\n",
              "  'body': 'I am trying to grab the maxresdefault of multiple YouTube thumbnails. Some YouTube videos simply don\\'t have a high res thumbnail photo so I want to catch that with an onError prop on an img element. For some reason my function is not triggering when I get the 404 img error. Any ideas? Thanks in advance.\\n\\nclass FeaturedVideo extends Component<Props> {\\n  addDefaultSrc = (e) => {\\n    e.target.src = this.props.background.replace(\"maxresdefault\", \"hqdefault\")\\n  }\\n\\n  renderVideo = (props) => (\\n    <div\\n      style={{\\n        width: \"100%\",\\n        height: \"100%\",\\n        backgroundSize: \"contain\",\\n      }}\\n      className=\"featured-community-video\"\\n    >\\n      <img onError={this.addDefaultSrc} src={props.background} alt=\"\" />\\n      <div className=\"featured-community-video-title\">\\n        <h2 style={{ fontSize: \"0.8em\" }}>WATCH</h2>\\n        <h1 style={{ fontSize: props.titleFontSize }}>{props.title}</h1>\\n      </div>\\n    </div>\\n  )\\n\\n  render() {\\n    return (\\n      <div\\n        key={this.props.postId}\\n        style={{\\n          width: this.props.width,\\n          height: \"50%\",\\n        }}\\n        className=\"featured-community-video-container\"\\n      >\\n        <Link to={routeCodes.POST_DETAILS(this.props.postId)}>\\n          {this.renderVideo(this.props)}\\n        </Link>\\n      </div>\\n    )\\n  }\\n}',\n",
              "  'answers': [{'body': '\\nTo achieve this, I would suggest rendering the <img /> based on the state of your <FeatureVideo/> component.\\n\\nYou could for instance, create an Image object, attempt to load the background  image and by this, reliably determine if the image fails to load. On the images success or failure to load, you would then setState() on your <FeaturedVideo/> component with the appropriate background value which would instead be used to rendering you actual <img/> element:\\n\\nclass FeaturedVideo extends Component<Props> {\\n\\n  componentDidMount() {\\n\\n    if(this.props.background) {\\n\\n      // When component mounts, create an image object and attempt to load background\\n      fetch(this.props.background).then(response => {\\n         if(response.ok) {\\n           // On success, set the background state from background\\n           // prop\\n           this.setState({ background : this.props.background })\\n         } else {        \\n           // On failure to load, set the \"default\" background state\\n           this.setState({ background : this.props.background.replace(\"maxresdefault\", \"hqdefault\") })\\n         }\\n      });\\n    }\\n  }\\n\\n  // Update the function signature to be class method to make state access eaiser\\n  renderVideo(props) {\\n\\n    return <div\\n      style={{\\n        width: \"100%\",\\n        height: \"100%\",\\n        backgroundSize: \"contain\",\\n      }}\\n      className=\"featured-community-video\">\\n\\n      {/* Update image src to come from state */}\\n\\n      <img src={this.state.background} alt=\"\" />\\n      <div className=\"featured-community-video-title\">\\n        <h2 style={{ fontSize: \"0.8em\" }}>WATCH</h2>\\n        <h1 style={{ fontSize: props.titleFontSize }}>{props.title}</h1>\\n      </div>\\n    </div>\\n  }\\n\\n  render() {\\n    return (\\n      <div\\n        key={this.props.postId}\\n        style={{\\n          width: this.props.width,\\n          height: \"50%\",\\n        }}\\n        className=\"featured-community-video-container\"\\n      >\\n        <Link to={routeCodes.POST_DETAILS(this.props.postId)}>\\n          {this.renderVideo(this.props)}\\n        </Link>\\n      </div>\\n    )\\n  }\\n}\\n\\n\\nHope that helps!\\n    ',\n",
              "    'score': None}],\n",
              "  'link': 'https://stackoverflow.com/questions/52999458/image-onerror-handling-in-react',\n",
              "  'tags': ['javascript',\n",
              "   'reactjs',\n",
              "   'image',\n",
              "   'youtube',\n",
              "   'onerror',\n",
              "   'javascript',\n",
              "   'reactjs',\n",
              "   'image',\n",
              "   'youtube',\n",
              "   'onerror']},\n",
              " {'title': 'Replace broken img with fallback picture',\n",
              "  'body': 'It\\'s really simple: if the link to a pic is broken a backup link steps in. I\\'ve googled this and it should be straight forward but I can\\'t get it working. I need to add it in Javascript and this is the line I\\'ve been trying to fix it with:\\n\\nvar issuePicFront = document.createElement(\"img\");\\nissuePicFront.id = \"first\" + count;\\nissuePicFront.src = issues[count].images.imageFront;\\nissuePicFront.onerror=\"this.src=replacePic\";\\nvar replacePic = https://www.jordans.com/~/media/jordans%20redesign/no-image-found.ashx?h=275&la=en&w=275&hash=F87BC23F17E37D57E2A0B1CC6E2E3EEE312AAD5B\\n\\n\\nI still get 404 (Not found). According to the majority och the internetz this is the common solution but don\\'t work for me.\\n\\nAny clues to solve this?',\n",
              "  'answers': [{'body': \"\\nYou should put quotes around the fallback URL (Assuming the rest of the code is working). \\n\\nI would also suggest to change the error handler to a function, like this:\\n\\nissuePicFront.onerror=function(e){\\n   var replacePic = '<URL>'\\n   this.src=replacePic;\\n};\\n\\n    \",\n",
              "    'score': None}],\n",
              "  'link': 'https://stackoverflow.com/questions/50857903/replace-broken-img-with-fallback-picture',\n",
              "  'tags': ['javascript', 'onerror', 'javascript', 'onerror']},\n",
              " {'title': '\"Script Error.\" errors in window.onerror in Safari only',\n",
              "  'body': 'I\\'m getting \"Script Error.\" when catching errors in window.onerror, even with properly (I think) configured CORS headers on S3.\\n\\nCORS config:\\n\\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\\n<CORSConfiguration xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\">\\n<CORSRule>\\n    <AllowedOrigin>*</AllowedOrigin>\\n    <AllowedMethod>GET</AllowedMethod>\\n    <AllowedMethod>POST</AllowedMethod>\\n    <AllowedMethod>PUT</AllowedMethod>\\n    <AllowedMethod>HEAD</AllowedMethod>\\n    <MaxAgeSeconds>3000</MaxAgeSeconds>\\n    <AllowedHeader>*</AllowedHeader>\\n</CORSRule>\\n</CORSConfiguration>\\n\\n\\nHTML:\\n\\n<script crossorigin src=\"https://s3.amazonaws.com/safari-script-error/foo.js\" />\\n\\n\\nwhich contains:\\n\\nwindow.addEventListener(\"keydown\", function(event) {\\n  if (event.keyCode === 69) { // \"e\" button\\n    throw new Error(\"Oh shoot\");\\n  }\\n});\\n\\n\\nJS:\\n\\nwindow.onerror = function(event) {\\n  console.log(event);\\n}\\n\\n\\nCodepen: https://codepen.io/astashov/pen/yoEvRB\\n\\nIt works fine in Chrome, Firefox and IE11, and only shows \"Script error.\" in Safari (I have Version 10.0.3 (12602.4.8)).\\n\\nHow to make it work in Safari too?',\n",
              "  'answers': [{'body': '\\n\\nHow to make it work in Safari too?\\n\\nYou can’t. Current Safari versions don’t support giving error messages to the onerror callback in the cross-origin case—even if a crossorigin attribute is specified on the script element.\\nSafari did support it previously, but subsequently regressed at some point.\\nThere’s an open bug for this at https://bugs.webkit.org/show_bug.cgi?id=132945\\n    ',\n",
              "    'score': None},\n",
              "   {'body': '\\nIt doesn\\'t appear that CORS is the problem. It appears that support for the global onerror handler isn\\'t in every browser.\\n\\nSee: \\nhttps://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror\\n\\nActually, it probably is related to CORS. \\n\\n\\n  When a syntax(?) error occurs in a script, loaded from a different origin, the details of the syntax error are not reported to prevent leaking information (see bug 363897). Instead the error reported is simply \"Script error.\" This behavior can be overriden in some browsers using the crossorigin attribute on  and having the server send the appropriate CORS HTTP response headers.  A workaround is to isolate \"Script error.\" and handle it knowing that the error detail is only viewable in the browser console and not accessible via JavaScript.\\n\\n    ',\n",
              "    'score': None}],\n",
              "  'link': 'https://stackoverflow.com/questions/45844565/script-error-errors-in-window-onerror-in-safari-only',\n",
              "  'tags': ['javascript',\n",
              "   'html',\n",
              "   'safari',\n",
              "   'cors',\n",
              "   'onerror',\n",
              "   'javascript',\n",
              "   'html',\n",
              "   'safari',\n",
              "   'cors',\n",
              "   'onerror']},\n",
              " {'title': 'window onerror filter out the addon/extension errors',\n",
              "  'body': \"I use a simple custom code to catch my js errors from my website. I use a window.onerror handler. However, I see that there are many addon/extension errors that users have installed into their browsers. I don't want to get those. Is there a way to filter those out and get only what is related to my code?\",\n",
              "  'answers': [{'body': '\\nI don\\'t know if this would work, but as mdn, there is a property in the ErrorEvent, the ErrorEvent is defined in here :\\naddEventListener(\"error\",function(err){\\nconsole.log(err) //Here it is your error, ErrorEvent\\n})\\n\\nNow, when you know the name of the javascript file, you can use the file, so you can filter the errors by file names :\\nerr.filename\\n\\nand if you are looking for chrome extensions, maybe it is near to impossible, as the chrome extensions are a part of the UI and therefore, a part of the window object\\n    ',\n",
              "    'score': None},\n",
              "   {'body': \"\\nFrom docs http://www.w3schools.com/js/js_window.asp\\n\\nThe window object is supported by all browsers. It represents the browser's window.\\nAll global JavaScript objects, functions, and variables automatically become members of the window object.\\nGlobal variables are properties of the window object.\\nGlobal functions are methods of the window object.\\nEven the document object (of the HTML DOM) is a property of the window object.\\n\\nSo that's why addons error appears in your catch block. \\n\\nBut from this.\\n\\nhttps://developer.mozilla.org/en/docs/Web/API/GlobalEventHandlers/onerror \\n\\nI would suggest you inside onError handler check messages and sources to see if this error corresponds to your code. If not just ignore it.\\n\\nHope this helps.\\n    \",\n",
              "    'score': None},\n",
              "   {'body': \"\\ne.stack includes URLs to the triggering script, so with that you can filter only for first-party scripts. Keep note that e.stack is non-standard, but widely supported.\\nwindow.addEventListener('error', e => {\\n  if (e.error?.stack?.includes(window.location.origin)) {\\n    // handle first-party error\\n  }\\n});\\nwindow.addEventListener('unhandledrejection', e => {\\n  if (e.reason?.stack?.includes(window.location.origin)) {\\n    // handle first-party error\\n  }\\n});\\n\\n    \",\n",
              "    'score': None},\n",
              "   {'body': \"\\nJust use event listeners like this:\\nwindow.addEventListener('error', (e) => {\\n    console.log(e);\\n});\\n\\nEvent handlers (like window.onerror) are only useful for ancient browsers.\\n    \",\n",
              "    'score': None}],\n",
              "  'link': 'https://stackoverflow.com/questions/39558524/window-onerror-filter-out-the-addon-extension-errors',\n",
              "  'tags': ['javascript', 'onerror', 'javascript', 'onerror']},\n",
              " {'title': 'Is it possible to override native fetch api to use a desired Promise library instead of native browser Promise?',\n",
              "  'body': \"Here is what I mean.\\n\\nIf the browser natively supports fetch api (for example, Chrome), then it uses the native browser Promise.\\n\\nIf I use another Promise library, (like bluebird, for example), native fetch still isn't using it — it uses native Promise implementation instead.\\n\\nIs there a way to override that?\\n\\nProblem example:\\n\\nwindow.Promise = function () { return null; };\\n\\n\\nfetch('/api')\\n.then(function (res) {\\n    console.log('fetch result!', res); // still works because it uses native Promise\\n});\\n\\n\\nWhy would I need that, you may be wondering? I wish to make use global rejection events which bluebird library supports and native Promises don't have.\",\n",
              "  'answers': [{'body': \"\\nHere's some code that goes along the same line as @MinusFour suggested. Replace global with window if you're in a browser and not inside a module.\\n\\nconst fetch = global.fetch\\nglobal.fetch = function() {\\n    return Promise.resolve(fetch.apply(global, arguments))\\n}\\n\\n    \",\n",
              "    'score': None},\n",
              "   {'body': \"\\nYou could use bluebird Promise.resolve() on the fetch promise. It will create a bluebird promise that assimilates fetch promise.\\n\\nPromise.resolve(Promise|any value) -> Promise\\n\\nCreate a promise that is resolved with the given value. If value is already a trusted Promise, it is returned as is. If value is not a thenable, a fulfilled Promise is returned with value as its fulfillment value. If value is a thenable (Promise-like object, like those returned by jQuery's $.ajax), returns a trusted Promise that assimilates the state of the thenable.\\n\\n\\nhttp://bluebirdjs.com/docs/api/promise.resolve.html\\n    \",\n",
              "    'score': None},\n",
              "   {'body': \"\\nI found this too and thought it might make sense to post it here -\\nhttps://github.com/github/fetch/issues/417\\n\\nThe post says (in case the link in broken) - \\nif you want to use bluebird in browser, use this, and\\n\\n\\n  window.fetch = null\\n  \\n  window.Promise = bluebird\\n  \\n  require('whatwg-fetch') the latest version browser may have fetch API\\n  already, this repo will return false if there is fetch API.\\n  \\n  if you want to use bluebird in node, use node-fetch, and\\n  \\n  let fetch = require('node-fetch');\\n  \\n  fetch.Promise = bluebird\\n\\n    \",\n",
              "    'score': None}],\n",
              "  'link': 'https://stackoverflow.com/questions/35367266/is-it-possible-to-override-native-fetch-api-to-use-a-desired-promise-library-ins',\n",
              "  'tags': ['javascript',\n",
              "   'error-handling',\n",
              "   'es6-promise',\n",
              "   'onerror',\n",
              "   'fetch-api',\n",
              "   'javascript',\n",
              "   'error-handling',\n",
              "   'es6-promise',\n",
              "   'onerror',\n",
              "   'fetch-api']},\n",
              " {'title': 'On Error GoTo only working once for analyzing input box value',\n",
              "  'body': 'I have a spreadsheet that tracks the time various files are sent.  For each file I have an input box that asks for the time the file sent, and there are a few other options that can be put in that input box.  \\n\\nIf the person does not enter a valid entry, I would like to send them back to the input box so they can try again.  \\n\\nThis is my code, which works for the first error, but if someone enters the wrong value a second time, they just get the standard \\'Type Mismatch\\' error.  I am creating this for people who don\\'t have any knowledge of VBA and would like to make it as easy as possible.  \\n\\nThere are multiple instances of the following code, each for a different file time.  Thanks in advance!\\n\\nCFP:\\nIf Err Then MsgBox Error & \" Invalid value.  Please enter only \\'blank\\', \\'holiday\\', \\'skip\\' or time value.\"\\nErr.Clear\\ntm = UCase(Application.InputBox(\"What time was the CFP file sent?\"))\\n\\nOn Error GoTo CFP\\nIf tm = \"BLANK\" Then\\n    ActiveCell.Value = \"Blank\"\\nElseIf tm = \"HOLIDAY\" Then\\n    ActiveCell.Value = \"Holiday\"\\nElseIf tm = \"SKIP\" Then\\n        ActiveCell.Value = \"Skipped\"\\nElse\\n    ActiveCell.Value = TimeValue(tm)\\nEnd If',\n",
              "  'answers': [{'body': '\\nRather than using the error handler, I would use a Loop that would break only when the condition is met. For example: \\n\\nAsk the first time:\\n\\ntm = UCase(Application.InputBox(\"What time was the CFP file sent?\"))\\nDim inputOK As Boolean\\n\\n\\nKeep on asking until the user enters wrong values:\\n\\ninputOK = checkMyInput(tm) \\'<-- is the input \"tm\" ok or not?\\nDo While inputOK = False \\'<-- if it\\'s not ok, keep on asking\\n    MsgBox \"Please enter a valid input\"\\n    tm = UCase(Application.InputBox(\"What time was the CFP file sent?\"))   \\n    inputOK = checkMyInput(tm) \\'<-- and checking it again...\\nLoop\\n\\n\\nwhere checkMyInput(tm) would be a custom function returning True or False if your input is ok or not:\\n\\nFunction checkMyInput(ByVal tm As Variant) As Boolean\\n    If tm =\"BLANK\" Or tm = \"HOLIDAY\" Or tm = \"SKIP\" Or IsDate(tm) Then\\n        checkMyInput = True\\n    Else\\n        checkMyInput = False\\n    End If\\nEnd Function\\n\\n    ',\n",
              "    'score': None},\n",
              "   {'body': \"\\nError handlers go below the procedure they're handling errors for:\\n\\nPublic Sub DoSomething\\n    On Error GoTo ErrHandler\\n\\n    'code here\\n\\nCleanup:\\n    'cleanup code here\\n    Exit Sub\\n\\nErrHandler:\\n    'error-handling code here\\n    Resume Cleanup\\nEnd Sub\\n\\n\\nWhat's happening is that once the first error is raised, because the error handler label is at the top, instead of jumping down into the error handler, the code jumps up back to the top, and VBA understands the rest of the procedure to be the error-handling subroutine... which never returns to the actual procedure body, because it is the procedure's body.\\n\\nYou're using the wrong control flow structure for the job, see @Matteo's answer for what you need.\\n    \",\n",
              "    'score': None}],\n",
              "  'link': 'https://stackoverflow.com/questions/29951610/on-error-goto-only-working-once-for-analyzing-input-box-value',\n",
              "  'tags': ['vba', 'excel', 'onerror', 'vba', 'excel', 'onerror']},\n",
              " {'title': 'Return JSONP from OnError Pipeline using NancyFX',\n",
              "  'body': \"I've got a simple API that is returning JSON.\\nThere is a use case for certain clients to require a JSONP response.\\n\\nNancy returns JSONP naturally if you provide a callback parameter (super happy awesome!).\\n\\nUnfortunately, when I'm trying to handle exceptions, I'm just getting JSON back when I return a Nancy response.\\nSeems like the JSONP functionality is only baked into the AfterRequest pipeline?\\n\\nMy error handling:\\n\\npublic class ErrorHandlingStartup : IApplicationStartup\\n{\\n    public void Initialize(IPipelines pipelines)\\n    {\\n        pipelines.OnError.AddItemToEndOfPipeline((ctx, exception) =>\\n        {\\n            var response = ErrorResponse.FromException(exception);\\n\\n            return response;\\n        });\\n    }\\n}\\n\\n\\nThe nancy JsonP class:\\nhttps://github.com/NancyFx/Nancy/blob/master/src/Nancy/Jsonp.cs\\n\\nIs there anything simple that I'm missing or do I need implement the JsonP functionality to also cover OnError?\",\n",
              "  'answers': [],\n",
              "  'link': 'https://stackoverflow.com/questions/27845582/return-jsonp-from-onerror-pipeline-using-nancyfx',\n",
              "  'tags': ['asp.net',\n",
              "   'api',\n",
              "   'jsonp',\n",
              "   'nancy',\n",
              "   'onerror',\n",
              "   'asp.net',\n",
              "   'api',\n",
              "   'jsonp',\n",
              "   'nancy',\n",
              "   'onerror']},\n",
              " {'title': 'Changing an image src on the fly with Javascript',\n",
              "  'body': 'I\\'m trying to change the src of some img tags if/when there is a problem with the pics when loading the page.  I seem to be getting some random behavior particularly from Internet Explorer 9.  Some of the images show the replaced image correctly and some have a red cross on them.  If I debug in the browser I\\'m told that ImgError() is not defined.  It\\'s clearly defined in the code and is obviously working.  Why is this happening?\\n\\n<div class=\"PhotoBorder\"><img alt=\"\" onerror=\"imgError(this)\" \\n    src=\"./images/services/69_Staffmember.jpg\" /></div>\\n\\n<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js\">           \\n    </script>  \\n\\n<script> \\n$(window).load( function() {\\n    $(\\'.RowWrapper\\').each(function() {\\n        var TotalWidth = 0;\\n        $(this).find(\\'.StaffMember\\').each(function() {\\n            TotalWidth = TotalWidth + $(this).outerWidth(true);     \\n        });\\n        this.style.width = TotalWidth + \"px\";           \\n    });\\n});\\n\\nfunction imgError(img)\\n{ \\n    img.setAttribute(\"src\",\"./images/services/49_ImgMissing.jpg\");  \\n    img.removeAttribute(\"onerror\");\\n}     \\n\\n</script>',\n",
              "  'answers': [{'body': \"\\nFirstly, if you're getting the error that ImgError() is not defined it's because your function name is imgError, not ImgError(). \\n\\nBut, if that was a typo in your question then it's possible that you're getting the error imgError() is not defined at some points because chances are the image is being requested from the cache and it's error handler is firing instantaneously - i.e. before the rest of your document has been parsed meaning that your imgError function is not yet available. To fix it, just put your imgError function in a script tag in the head of your document.\\n    \",\n",
              "    'score': None},\n",
              "   {'body': '\\nGive your image element an id and try this:\\n\\ndocument.getElementById(\"imageid\").src=\"./images/services/49_ImgMissing.jpg\";\\n\\n    ',\n",
              "    'score': None},\n",
              "   {'body': \"\\nI'm answering on behalf of RobG.  The definition of imgError() was below where it was being called in my code.  You must position your code definitions above where you make calls in your html.  Otherwise your results may be undefined as I found out.\\n    \",\n",
              "    'score': None}],\n",
              "  'link': 'https://stackoverflow.com/questions/22752133/changing-an-image-src-on-the-fly-with-javascript',\n",
              "  'tags': ['javascript',\n",
              "   'html',\n",
              "   'image',\n",
              "   'onerror',\n",
              "   'javascript',\n",
              "   'html',\n",
              "   'image',\n",
              "   'onerror']}]"
            ]
          },
          "metadata": {},
          "execution_count": 18
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "AyXjt9dsDxUq"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}